spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root

server:
  error:
    include-stacktrace: never